Implemented UI for the Tab displaying infos on an activity when clicked
LASTA-OUTDOOR/lasta pull request #122
Opened 2024-04-18 13:37 UTC by ecornamu

The UI looks like this 
![image](https://github.com/LASTA-OUTDOOR/lasta/assets/100190035/7eb8a03f-acb4-42e6-b7a2-b4ddc0a507ea)
and is based on the Figma mockup for this tab.
- It is already tested for a line coverage of 80% (can be improved if needed)
- The current state of the app doesn't include an `address` attribute for `OutdoorActivity` nor a picture of the activity. Thus, both features are not displayed on the UI yet but can be done as soon as those attributes are a thing.
- Same for the `Community` tab, implemented as a `Spacer` here but can be added afterwards
- Since this is strictly UI, every button doesn't do anything yet.
- There is a helper function that should be put in a `ViewModel`, which I will do later but since it doesn't change functionality I instantiated the PR without this change but it will be done

2024-04-18 13:45 UTC, Andy130604 commented on app/src/main/res/drawable/archive.png
This is a download button, not archive make sure to rename this

2024-04-18 13:48 UTC, Andy130604 commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
We'll have to look into naming of these files, maybe have the screen called MoreInfoScreen.kt inside moreinfo package would make more sense. You could have a composable named ActivityDisplay or whatever.

2024-04-19 10:50 UTC, Thimphou requested changes
Hi Emile! 

Your UI work looks great, it is tested, and the Android tests look fine to me. 

Your code is commented, and maybe restructuring as Andrew said would increase our code usability. 

Now that the Color theme implementation is merged on main, I would like you not to hardcode the Colors anymore, but start coding it with the app's colors. 

Otherwise, great code!

2024-04-19 10:55 UTC, Thimphou reviewed
I added a few comments on your code.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF0096CF))) {
Just change the color used here!

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF0096CF))) {
Here as well.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +        tint = Color(0, 150, 207, 255),
Here, you could either use the "yellow" hardcoded value of the star, or the blue/green of our app.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +      colors = ButtonDefaults.buttonColors(containerColor = Color(0xCCFFE713))) {
Here as well.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +                    color = Color(0xFF000000),
Here for the dark mode.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +        tint = Color(0, 150, 207, 255))
Here as well to use the green or blue of Lasta.

2024-04-19 10:55 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/activities/ActivityScreen.kt
> +      colors = ButtonDefaults.buttonColors(containerColor = Color(0, 150, 207, 128))) {
And lastly, here!

2024-04-19 10:58 UTC, Thimphou approved these changes

2024-04-19 16:53 UTC, ecornamu commented
Handled both requests ! With more details : 
- Colors of the UI are now using either the lasta theme default ones or the ones defined in `Color.kt`
- Image is now renamed `download_button` (previously `archive`, pickiest request I've had lol)
- The `MoreInfoScreen` is now connected to both the `FavoritesScreen` and the `DiscoveryScreen` when you click on an activity. For the moment, a fake activity is hard-coded and displayed but it will be replaced by the real requested activity when we have a view model

2024-04-19 17:01 UTC, Thimphou commented
Life is now better than ever! Thank you for your changes :)

2024-04-19 18:50 UTC, Andy130604 approved these changes
These are some nice changes, not so sure about your navigation implementation, I hope you'll look into it for the next sprint. Otherwise really nice design

2024-04-19 20:17 UTC, ecornamu commented
Last commits were because @Andy130604 and I were trying to fix a `test` not passing, whose solution ended up being to clear the cache of the CI server

2024-04-19 20:17 UTC, merged