More info/go to map
LASTA-OUTDOOR/lasta pull request #196
Opened 2024-05-01 18:16 UTC by npfrei

Allows user to click on the "go to Map" button in the moreInfo tab. I could not really test what I added, as it relies on a map tab that's almost impossible to Test. But, I added tests for the rest of the moreInfo screen to see that everything was displayed properly.

2024-05-01 20:27 UTC, CassioManuguerra requested changes
Hello Nehemie, 

your PR is really good the button works fine and the code is neat, although I'm a bit perplexed because when I run your code it seems that all the activities, when you press viewOnMap, take you to a location south of Ghana in the Atlantic Ocean. If it is not the case on your end, maybe you could put some indications on how you can obtain a correct result ?

Apart from this and some functions that are lacking a bit of commenting, you did some great job, handling the map is not easy (🥶) and you managed to do so pretty well !
A few suggestions/notes for next updates (if we have time for it ^^) : 
- Show the other markers around the selected one that is being displayed on the map even if it is not the one that was opened under more info, because if the user is looking for this activity, he/she could be interested in seeing other activities around !
- The UI for the dialog popping under the map will maybe have to be revisited quite a bit, as for now it is not looking great

2024-05-01 20:27 UTC, CassioManuguerra commented on app/src/main/java/com/lastaoutdoor/lasta/ui/navigation/MainNavGraph.kt
There are a lot of parameters passed to instance a MoreInfoScreen now, maybe it is possible to remove some that are not mandatory ?

2024-05-01 20:27 UTC, CassioManuguerra commented on app/src/main/java/com/lastaoutdoor/lasta/ui/screen/map/MapScreen.kt
> +
This block would look better commented ;-)

2024-05-01 20:27 UTC, CassioManuguerra commented on app/src/main/java/com/lastaoutdoor/lasta/viewmodel/MoreInfoScreenViewModel.kt
> +  fun goToMarker(activity: Activity): com.lastaoutdoor.lasta.models.map.Marker {
It would be nice if you could comment the goToMarker function !

2024-05-01 21:18 UTC, npfrei commented on app/src/main/java/com/lastaoutdoor/lasta/ui/navigation/MainNavGraph.kt
Hi, thanks for your comment ! The issue with the points appearing in the middle of Ocean comes from the refactoring of database fuction, so it is not part of my PR. It will be fixed in Andrew's next one.

2024-05-01 21:22 UTC, npfrei commented on app/src/main/java/com/lastaoutdoor/lasta/ui/navigation/MainNavGraph.kt
> There are a lot of parameters passed to instance a MoreInfoScreen now, maybe it is possible to remove some that are not mandatory ?

I don't think it is possible without changing (again lol) the architecture of the project, as the mapScreen needs a lot of arguments to be created correctly, but I could look into it in another sprint

2024-05-02 08:22 UTC, CassioManuguerra commented on app/src/main/java/com/lastaoutdoor/lasta/ui/navigation/MainNavGraph.kt
Okay thanks ! I am reassured

2024-05-02 16:39 UTC, CassioManuguerra approved these changes
It's good ! LGTM

2024-05-03 11:55 UTC, merged