Weather/forecastnotif
LASTA-OUTDOOR/lasta pull request #301
Opened 2024-05-22 21:32 UTC by ecornamu

2024-05-23 15:56 UTC, Thimphou requested changes
Hey Emile!

Your feature will greatly help our users advise their future activities, it is very desirable and it add a lot of value.

Although, I think it is possible to get those 4 remaining percents to achieve 80% line coverage, I'm sure you will successfully do it :)

2024-05-23 15:56 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/data/api/weather/WeatherApiResponse.kt
Great code, and good job using data classes!

2024-05-23 15:56 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/components/WeatherReport.kt
>  private const val KELVIN_CONST = 273.15
This constant is not used anymore, you could move it in `WeatherApiResponse.kt`

2024-05-23 15:56 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/ui/components/WeatherReport.kt
This composable seems well implemented, thank you for putting the report into a Card, it is much more aestethic.

2024-05-23 15:56 UTC, Thimphou commented on app/src/main/java/com/lastaoutdoor/lasta/viewmodel/WeatherViewModel.kt
> +        // forecast for activity location
Great reflex to put it inside the try block, so the ErrorToast handle the error :)

2024-05-23 16:34 UTC, CassioManuguerra requested changes
Solid PR my g !
Having the weather forecasts is such a useful feature to our app, nice job on getting it done ! Your code is really nice, you commented (feels so good), you tested (as much as possible).

It is just a bit sad that you didn't get the 80%, are you sure you cannot test the weatherViewModel ? Please try testing it using a blank Application() call !

Another thing that I think is important would be to implement a back arrow for the small dialog opening, the one on your photo looks a bit "unprofessional" or "drafty".

Thanks in advance for trying to fix these, good job once again,
Cassio

2024-05-23 21:06 UTC, ecornamu commented
Hey @Thimphou and @CassioManuguerra, thank you both for your feedback ! I added further testing to increase line coverage to 84% thanks to some big help from @CassioManuguerra. 
The only requested change I didn't implement is the arrow on the Forecast Card, because I don't agree with its addition to the UI and I think we need to discuss this with the team and maybe change this later.

2024-05-23 22:26 UTC, Thimphou approved these changes
Changes are looking good, thank you for your quick  adjustments.

2024-05-24 06:57 UTC, CassioManuguerra approved these changes
Thanks for changing, great job on testing, approving now !!!

2024-05-24 07:29 UTC, merged